repo_name: cicd_demo_11
owner: GreatBat67
project_name: github_cicd_demo_12
default_branch: dev
branches:
  dev:
    protection:
      require_pr: false
      required_approvals: 0
    approvers:
      groups: []
      individuals: &id001 []
    environment: dev
    environment_reviewers:
      groups: []
      individuals: *id001
  qa:
    protection:
      require_pr: true
      required_approvals: 1
    approvers:
      groups: []
      individuals: &id002
      - GreatBat67
    environment: qa
    environment_reviewers:
      groups: []
      individuals: *id002
    source_branch: dev
  cicd:
    protection:
      require_pr: true
      required_approvals: 1
    approvers:
      groups: []
      individuals: &id003
      - GreatBat67
    environment: cicd
    environment_reviewers:
      groups: []
      individuals: *id003
    source_branch: qa
  main:
    protection:
      require_pr: true
      required_approvals: 1
      lock_branch: true
      restrict_pushes: true
    approvers:
      groups: []
      individuals: &id004
      - GreatBat67
    environment: main
    environment_reviewers:
      groups: []
      individuals: *id004
    source_branch: cicd
    locked: true
final_branch: main
