create or replace task INGEST_HOSPITAL_DETAILS
	warehouse=DISHA_RANI_WH
	schedule='USING CRON 00 13 * * * Asia/Kolkata'
	as COPY INTO CICD_AUTOMATION_PROD.HOSPITALS.HOSPITAL_DETAILS
FROM @CICD_AUTOMATION_PROD.HOSPITALS.HOSPITALS_STAGE
FILE_FORMAT = (FORMAT_NAME = 'CICD_AUTOMATION_PROD.UTILITIES.CSV');