dcm_dbt_cicd:
  target: dev

  outputs:

    dev:
      type: snowflake
      account: KIPI-KIPI_PRIMARY
      user: github_cicd_demo_dev_user
      role: DBA_ADMIN
      database: CICD_DEMO_DEV
      warehouse: github_cicd_demo_wh
      schema: UTILITIES
      threads: 4
      client_session_keep_alive: false

    qa:
      type: snowflake
      account: KIPI-KIPI_PRIMARY
      user: github_cicd_demo_qa_user
      role: DBA_ADMIN
      database: CICD_DEMO_QA
      warehouse: github_cicd_demo_wh
      schema: UTILITIES
      threads: 4
      client_session_keep_alive: false

    cicd:
      type: snowflake
      account: KIPI-KIPI_PRIMARY
      user: github_cicd_demo_cicd_user
      role: DBA_ADMIN
      database: CICD_DEMO_CICD
      warehouse: github_cicd_demo_wh
      schema: UTILITIES
      threads: 4
      client_session_keep_alive: false

    prod:
      type: snowflake
      account: KIPI-KIPI_PRIMARY
      user: github_cicd_demo_prod_user
      role: DBA_ADMIN
      database: CICD_DEMO_PROD
      warehouse: github_cicd_demo_wh
      schema: UTILITIES
      threads: 4
      client_session_keep_alive: false
