name: "Snowflake Component: Progression Target - main"
on:
  workflow_call:

env:
  SNOWFLAKE_ACCOUNT: "KIPI-KIPI_PRIMARY"
  SNOWFLAKE_ROLE: "PSEUDO_ACCOUNTADMIN"
  SNOWFLAKE_WAREHOUSE: "github_cicd_demo_wh"
  SNOWFLAKE_CLI_FEATURES_ENABLE_SNOWFLAKE_PROJECTS: "true"
  SNOWFLAKE_DATABASE: "CICD_DEMO_PROD"
  SNOWFLAKE_SCHEMA: "UTILITIES"

jobs:
  main-environment-plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: main 
    steps:
      - uses: actions/checkout@v4

      - name: Run Modular Infrastructure Verification (DCM Plan)
        uses: ./.github/workflows/modules/action-dcm-engine
        with:
          dcm_dir: "dcm_automation"
          dcm_target: "DCM_PROD"
          action_type: "plan"

      - name: Run Modular Data Transformation Verification (dbt Plan)
        uses: ./.github/workflows/modules/action-dbt-engine
        with:
          dbt_dir: "./dcm_dbt_cicd"
          dbt_project: "dbt_project_dev"
          dcm_target: "DCM_PROD"
          action_type: "plan"

  main-environment-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: main 
    steps:
      - uses: actions/checkout@v4

      - name: Live Deploy to Database Target (DCM Deploy)
        uses: ./.github/workflows/modules/action-dcm-engine
        with:
          dcm_dir: "dcm_automation"
          dcm_target: "DCM_PROD"
          action_type: "deploy"

      - name: Live Database Content Transformations (dbt Deploy)
        uses: ./.github/workflows/modules/action-dbt-engine
        with:
          dbt_dir: "./dcm_dbt_cicd"
          dbt_project: "dbt_project_prod"
          dcm_target: "DCM_PROD"
          action_type: "deploy"

